<?php
$title = 'Delete Album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Вы уверены, что хотите удалить <?php echo $this->escapeHtml($album->title); ?> артиста
    <?php echo $this->escapeHtml($album->artist); ?>?</p>
<?php
$url = $this->url('album', array('action' => 'delete', 'id' => $this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int)$album->id; ?>" />
        <input type="submit" name="del" value="Да" />
        <input type="submit" name="del" value="Нет" />
    </div>
</form>
