<?php
$title = 'Albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Number</th>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
    <tr>
<!--        <td>--><?php //for($i=1; $i = 8; $i++){echo $this->escapeHtml($i);}; ?><!--</td>-->
        <td><?php echo $this->escapeHtml($album['id']); ?></td>
        <td><a href="<?php echo $this->url('album', array('action' => 'get_album', 'id' => $album['id'])); ?>"><?php echo $this->escapeHtml($album['title']); ?></a></td>
        <td><?php echo $this->escapeHtml($album['name']); ?></td>
        <td>
            <a href="<?php echo $this->url('album', array('action' => 'get_album', 'id' => $album['id'])); ?>">Details&nbsp;</a>
            <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album['id'])); ?>">Edit&nbsp;</a>
            <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album['id'])); ?>">Delete</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
