<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles Everything has got to go on, somehow or other-->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
//    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/css/style.css'); ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar">
                <span class="icon-bar">&nbsp;</span>
                <span class="icon-bar">&nbsp;</span>
                <span class="icon-bar">&nbsp;</span>
            </a>
            <a class="brand"
               href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Everything has got to go on, somehow or other') ?></a>
            <?php echo $this->navigation('navigation')
            ->menu()->setMinDepth(0)->setMaxDepth(0)->setUlClass('nav')->render(); ?>
        </div>
    </div>
</div>
<div class="container">
    <?php echo $this->navigation('navigation')
    ->breadcrumbs()->setMinDepth(0)
    ->setPartial(array('partial/breadcrumb.phtml', 'Альбомы')); ?>
    <?php echo $this->content; ?>
    <hr/>
    <div>
        <p>&copy; 2013 <?php if (date('Y') > 2013) {
            echo '- ' . date('Y');
        } ?> <?php echo sprintf('Пытается работать на %sZend Framework%s версии %s - %s.', '<a href="https://github.com/zendframework/ZendSkeletonApplication">', '</a>', \Zend\Version\Version::VERSION, 'Тормозит очень сильно') ?> <?php echo $this->translate('All rights reserved.') ?></p>
    </div>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
