<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Blog\Module'                                     => __DIR__ . '/Module.php',
    'Blog\Controller\BlogController'                  => __DIR__ . '/src/Blog/Controller/BlogController.php',
    'Blog\Form\AlbumFieldset'                         => __DIR__ . '/src/Blog/Form/AlbumFieldset.php',
    'Blog\Form\AlbumForm'                             => __DIR__ . '/src/Blog/Form/AlbumForm.php',
    'Blog\Form\ArtistFieldset'                        => __DIR__ . '/src/Blog/Form/ArtistFieldset.php',
    'Blog\Form\View\Helper\Captcha\CustomCaptcha'     => __DIR__ . '/src/Blog/Form/View/Helper/Captcha/CustomCaptcha.php',
    'Blog\Form\View\Helper\Captcha\ViewHelperCaptcha' => __DIR__ . '/src/Blog/Form/View/Helper/Captcha/ViewHelperCaptcha.php',
    'Blog\Form\View\Helper\FormElementErrors'         => __DIR__ . '/src/Blog/Form/View/Helper/FormElementErrors.php',
    'Blog\Model\AbstractMapper'                       => __DIR__ . '/src/Blog/Model/AbstractMapper.php',
    'Blog\Model\Album'                                => __DIR__ . '/src/Blog/Model/Album.php',
    'Blog\Model\AlbumMapper'                          => __DIR__ . '/src/Blog/Model/AlbumMapper.php',
    'Blog\Model\Artist'                               => __DIR__ . '/src/Blog/Model/Artist.php',
    'Blog\Model\ArtistMapper'                         => __DIR__ . '/src/Blog/Model/ArtistMapper.php',
);
