<?php
// Generated by Zend Framework 2
return array(
    'Album\Module'                     => __DIR__ . '/Module.php',
    'Album\Controller\AlbumController' => __DIR__ . '/src/Album/Controller/AlbumController.php',
    'Album\Form\AlbumForm'             => __DIR__ . '/src/Album/Form/AlbumForm.php',
    'Album\Model\Album'                => __DIR__ . '/src/Album/Model/Album.php',
    'Album\Model\AlbumTable'           => __DIR__ . '/src/Album/Model/AlbumTable.php',
    'Album\TestModel\AlbumTest'        => __DIR__ . '/test/AlbumTest/Model/AlbumTest.php',
);