<?php
$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('blog', array('action' => 'add')));
$form->get('submit')->setValue('Add');
echo$this->form()->openTag($form);
$album = $form->get('album');
echo '<div>' . $this->formHidden($album->get('id'));
echo $this->formRow($album->get('title')) . '<br/>';
echo $this->formRow($album->get('artist')) . '<br/>';
echo $this->formElement($form->get('submit'));
echo '</div>' . $this->form()->closeTag();